# https://taskfile.dev

version: "3"

tasks:
  default:
    cmds:
      - task -f
    silent: true

  lint:
    cmds:
      - ansible-lint .

  converge:
    cmds:
      - molecule converge
  test:
    cmds:
      - molecule test
